EventManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('tickets/', include('payments.urls')),
    path('reports/', include('reports.urls')),
]

events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomepageView.as_view(), name='homepage'),
    path('events/', views.EventListView.as_view(), name='events'),
    path('events/create', views.EventCreateView.as_view(), name='create_event'),
    path('events/<slug:slug>', views.EventDetailView.as_view(), name='event_detail'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Create your models here.

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=350)

    def __str__(self):
        return self.comment

class Event(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=150, blank=True, null=True)
    description = models.TextField()
    place = models.CharField(max_length=300)
    time = models.DateField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, blank=True)
    tickets_amount = models.IntegerField(null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

events/forms.py
from django import forms
from .models import Comment, Event
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ("user", )

class EventForm(forms.ModelForm):
    class Meta:
        model=Event
        fields=['title', 'subtitle', 'description', 'time', 'place', 'tickets_amount', 'price']
        widgets={'time': forms.DateInput(attrs={'type': 'date'})}

events/views.py
from django.shortcuts import  redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, FormView, CreateView, ListView, DetailView
from django.urls import reverse_lazy
from .forms import CommentForm, CustomUserCreationForm, EventForm
from .models import Comment, Event
import json
from django.core.serializers.json import DjangoJSONEncoder

# Create your views here.

class HomepageView(FormView):
    template_name = "events/homepage.html"
    form_class = CommentForm
    success_url = "/"
    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        comments = list(Comment.objects.order_by("-id"))
        if comments:
            context["comment_first"] = Comment.objects.order_by("-id")[0]
            context["comments"] = Comment.objects.order_by("-id")[1:4]
        else:
            context["comment_first"] = None  # No comments available
            context["comments"] = []  # Empty list of comments
        return context

class EventListView(ListView):
    model = Event
    template_name = 'events/events.html'
    context_object_name = 'events'

    def get_queryset(self):
        sort_by = self.request.GET.get('sort_by', 'time')
        allowed_sort_fields = ['time', 'place', 'title', 'creator__username']
        if sort_by not in allowed_sort_fields:
            sort_by = 'time'
        return Event.objects.all().order_by(sort_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events = self.get_queryset()
        events_data = []
        for event in events:
            place_coords = event.place.split(',')
            place_lat = float(place_coords[0])
            place_lng = float(place_coords[1])
            events_data.append({
                'id': event.id,
                'title': event.title,
                'subtitle': event.subtitle,
                'place_lat': place_lat,
                'place_lng': place_lng,
                'time': event.time.isoformat(),
                'creator_username': event.creator.username,
            })
        context['events_data'] = json.dumps(events_data, cls=DjangoJSONEncoder)
        return context

class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    context_object_name = 'event'

    def get_queryset(self):
        return Event.objects.filter(slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event_object = Event.objects.get(slug=self.kwargs['slug'])
        event_data = []
        place_coords = event_object.place.split(',')
        place_lat = float(place_coords[0])
        place_lng = float(place_coords[1])
        event_data.append({
            'id': event_object.id,
            'title': event_object.title,
            'subtitle': event_object.subtitle,
            'place_lat': place_lat,
            'place_lng': place_lng,
            'time': event_object.time.isoformat(),
            'creator_username': event_object.creator.username,
            })
        context['events_data'] = json.dumps(event_data, cls=DjangoJSONEncoder)
        return context

class RegisterView(FormView):
    template_name = 'events/registration.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

class LoginView(FormView):
    template_name = 'events/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)

class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('homepage')

class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm
    template_name = 'events/create_event.html'
    success_url = reverse_lazy('events')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        place = self.request.POST.get('place')
        if place:
            form.instance.place = place

        return super().form_valid(form)

events/templates/events/create_event.html
{% extends 'base.html' %}

{% block title %}
Event Creation
{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
{% endblock %}

{% block content %}

    <style>
        #map {
            height: 400px;
            width: 100%;
            margin-top: 20px;
        }

        .btn-primary {
            background-color: #007bff;
            border: none;
            padding: 10px 20px;
            font-weight: 700;
            font-size: 16px;
            width: 100%;
            border-radius: 5px;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
        .container {
            max-width: 600px;
            margin-top: 550px;
            margin-bottom: 30px;
            background-color: white;
            padding: 50px;
            border-radius: 15px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        body {
            font-family: 'Roboto', sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container h2 {
            text-align: center;
            margin-bottom: 20px;
            font-weight: 700;
            color: #343a40;
        }
        .form-group label {
            font-weight: 700;
            color: #343a40;
        }
    </style>

        <h2>Create Event</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div id="map" class="my-3"></div>
            <button type="submit" class="btn btn-primary">Save Event</button>
        </form>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempus-dominus-bootstrap-4/5.39.0/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>

    <script>
        var map = L.map('map').setView([52.237, 21.01], 13);

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '© OpenStreetMap contributors'
        }).addTo(map);

        var marker;

        // Map click event listener
        map.on('click', function(e) {
            var lat = e.latlng.lat;
            var lng = e.latlng.lng;
            var place = lat + ', ' + lng;

            document.getElementById('id_place').value = place;

            if (marker) {
                marker.setLatLng(e.latlng);
            } else {
                marker = L.marker(e.latlng).addTo(map);
            }
        });
    </script>
{% endblock %}

events/templates/events/event_detail.html
{% extends 'base.html' %}

{% block title %}
Event Detail
{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block js_files %}
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}

<style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #cbf3f0;
            justify-content: center;
            height: 100vh;
        }
        .container {
            max-width: 1000px;
            margin-top: 50px;
            margin-bottom: 30px;
            background-color: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .container h2 {
            text-align: center;
            margin-bottom: 20px;
            font-weight: 700;
            color: #343a40;
        }
        .map-container {
        height: 200px;
        width: 300px;
        margin-bottom: 20px;
        }
</style>
        <h2>{{ event.title }}</h2>
        <p>{{ event.subtitle }}</p>
        <div id="map-{{ event.id }}" class="map-container"></div>
        <p><strong>Time:</strong> {{ event.time }}</p>
        <p><strong>Author:</strong> {{ event.creator.username }}</p>
    <div class="card">
        <div class="card-body d-flex align-items-center">
            <p class="mb-0">
                {{ event.description }}
            </p>
        </div>
    </div>
        <div class="card">
        <div class="card-body d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="46" height="46" fill="currentColor" class="bi bi-ticket ms-1" viewBox="0 0 16 16">
          <path d="M0 4.5A1.5 1.5 0 0 1 1.5 3h13A1.5 1.5 0 0 1 16 4.5V6a.5.5 0 0 1-.5.5 1.5 1.5 0 0 0 0 3 .5.5 0 0 1 .5.5v1.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 11.5V10a.5.5 0 0 1 .5-.5 1.5 1.5 0 1 0 0-3A.5.5 0 0 1 0 6zM1.5 4a.5.5 0 0 0-.5.5v1.05a2.5 2.5 0 0 1 0 4.9v1.05a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-1.05a2.5 2.5 0 0 1 0-4.9V4.5a.5.5 0 0 0-.5-.5z"/>
        </svg>
            <h3 class="mb-0 me-5 ms-3">
                Price: {{ event.price }}$
            </h3>
        </div>
        </div>
        <div class="card">
        <div class="card-body d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="46" height="46" fill="currentColor" class="bi bi-wallet ms-1" viewBox="0 0 16 16">
          <path d="M0 3a2 2 0 0 1 2-2h13.5a.5.5 0 0 1 0 1H15v2a1 1 0 0 1 1 1v8.5a1.5 1.5 0 0 1-1.5 1.5h-12A2.5 2.5 0 0 1 0 12.5zm1 1.732V12.5A1.5 1.5 0 0 0 2.5 14h12a.5.5 0 0 0 .5-.5V5H2a2 2 0 0 1-1-.268M1 3a1 1 0 0 0 1 1h12V2H2a1 1 0 0 0-1 1"/>
        </svg>
            <h3 class="mb-0 ms-3">
                Left: {{ event.tickets_amount }}
            </h3>
        </div>
        </div>
        </div>
    </div>
{% if user.is_authenticated %}
    <a href="{% url 'cart' event.id %}" class="btn btn-primary mt-5 me-3">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
            <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
        </svg> Buy Ticket
    </a>
{% else %}
    <a href="{% url 'login' %}" class="btn btn-primary mt-5 me-3">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
            <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
        </svg> Log in to buy
    </a>
{% endif %}
        <a href="{% url 'events' %}" class="btn btn-primary mt-5">Back to Events</a>

    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const events = JSON.parse('{{ events_data|escapejs }}');

            events.forEach(event => {
                const mapId = `map-${event.id}`;
                const mapContainer = document.getElementById(mapId);
                if (mapContainer) {
                    const map = L.map(mapId).setView([event.place_lat, event.place_lng], 13);
                    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                        attribution: '© OpenStreetMap contributors'
                    }).addTo(map);
                    L.marker([event.place_lat, event.place_lng]).addTo(map)
                        .bindPopup(`<b>${event.title}</b><br>${event.subtitle}`).openPopup();
                }
            });
        });
    </script>
{% endblock %}

events/templates/events/events.html
{% extends 'base.html' %}

{% block title %}
Events
{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
{% endblock %}

{% block js_files %}
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const events = JSON.parse('{{ events_data|escapejs }}');

        events.forEach(event => {
            const mapId = `map-${event.id}`;
            const mapContainer = document.getElementById(mapId);
            if (mapContainer) {
                const map = L.map(mapId).setView([event.place_lat, event.place_lng], 13);
                L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    attribution: '© OpenStreetMap contributors'
                }).addTo(map);
                L.marker([event.place_lat, event.place_lng]).addTo(map)
                    .bindPopup(`<b>${event.title}</b><br>${event.subtitle}`).openPopup();
            }
        });
    });
</script>
{% endblock %}

{% block content %}

<style>
    .map-container {
        height: 200px;
        width: 300px;
        margin-bottom: 20px;
    }
</style>

<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2>Event List</h2>
        {% if user.is_authenticated %}
        <a href="{% url 'create_event' %}" class="btn btn-success">
            <i class="fas fa-plus"></i> Add Event
        </a>
        {% endif %}
    </div>
    <div class="btn-group mb-4" role="group" aria-label="Sort buttons">
        <a href="?sort_by=time" class="btn btn-primary"><i class="fas fa-clock"></i> Sort by Time</a>
        <a href="?sort_by=place" class="btn btn-primary"><i class="fas fa-map-marker-alt"></i> Sort by Place</a>
        <a href="?sort_by=title" class="btn btn-primary"><i class="fas fa-heading"></i> Sort by Title</a>
        <a href="?sort_by=creator__username" class="btn btn-primary"><i class="fas fa-user"></i> Sort by Author</a>
    </div>
    <div class="event-container p-4 rounded shadow-sm bg-white">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Subtitle</th>
                    <th>Place</th>
                    <th>Time</th>
                    <th>Author</th>
                    <th>Tickets Amount</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for event in events %}
                    <tr>
                        <td><strong>{{ event.title }}</strong></td>
                        <td>{{ event.subtitle }}</td>
                        <td>
                            <div id="map-{{ event.id }}" class="map-container"></div>
                        </td>
                        <td>{{ event.time }}</td>
                        <td>{{ event.creator.username }}</td>
                        <td>{{ event.tickets_amount }}</td>
                        <td>{{ event.price }}</td>
                        <td>
                            <a href="{% url 'event_detail' event.slug %}" class="btn btn-info">
                                <i class="fas fa-info-circle"></i> View Details
                            </a>
                        </td>
                        {% if user.is_authenticated %}
                        <td>
                            <a href="{% url 'cart' event.id %}" class="btn btn-info">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                                <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
                                </svg> Buy Ticket
                            </a>
                        </td>
                        {% endif %}
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">No events available.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

events/templates/events/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Homepage {% endblock %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'events/homepage.css' %}">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6">
            <div class="row">
                <!-- Card 1 -->
                <div class="col-xl-6 col-lg-6 mb-4">
                    <div class="card l-bg-cherry">
                        <div class="card-statistic-3 p-4">
                            <div class="card-icon card-icon-large"><i class="fas fa-shopping-cart"></i></div>
                            <div class="mb-4">
                                <h5 class="card-title mb-0">Payments Made</h5>
                            </div>
                            <div class="row align-items-center mb-2 d-flex">
                                <div class="col-8">
                                    <h2 class="d-flex align-items-center mb-0">
                                        1,243
                                    </h2>
                                </div>
                            </div>
                            <div class="progress mt-1" data-height="8" style="height: 8px;">
                                <div class="progress-bar l-bg-cyan" role="progressbar" data-width="25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Card 2 -->
                <div class="col-xl-6 col-lg-6 mb-4">
                    <div class="card l-bg-blue-dark">
                        <div class="card-statistic-3 p-4">
                            <div class="card-icon card-icon-large"><i class="fas fa-users"></i></div>
                            <div class="mb-4">
                                <h5 class="card-title mb-0">Customers</h5>
                            </div>
                            <div class="row align-items-center mb-2 d-flex">
                                <div class="col-8">
                                    <h2 class="d-flex align-items-center mb-0">
                                        15.07k
                                    </h2>
                                </div>
                            </div>
                            <div class="progress mt-1" data-height="8" style="height: 8px;">
                                <div class="progress-bar l-bg-green" role="progressbar" data-width="25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Card 3 -->
                <div class="col-xl-6 col-lg-6 mb-4">
                    <div class="card l-bg-green-dark">
                        <div class="card-statistic-3 p-4">
                            <div class="card-icon card-icon-large"><i class="fas fa-ticket-alt"></i></div>
                            <div class="mb-4">
                                <h5 class="card-title mb-0">Ticket Resolved</h5>
                            </div>
                            <div class="row align-items-center mb-2 d-flex">
                                <div class="col-8">
                                    <h2 class="d-flex align-items-center mb-0">
                                        578
                                    </h2>
                                </div>
                            </div>
                            <div class="progress mt-1" data-height="8" style="height: 8px;">
                                <div class="progress-bar l-bg-orange" role="progressbar" data-width="25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Card 4 -->
                <div class="col-xl-6 col-lg-6 mb-4">
                    <div class="card l-bg-orange-dark">
                        <div class="card-statistic-3 p-4">
                            <div class="card-icon card-icon-large"><i class="fas fa-dollar-sign"></i></div>
                            <div class="mb-4">
                                <h5 class="card-title mb-0">Revenue Today</h5>
                            </div>
                            <div class="row align-items-center mb-2 d-flex">
                                <div class="col-8">
                                    <h2 class="d-flex align-items-center mb-0">
                                        $11.61k
                                    </h2>
                                </div>
                            </div>
                            <div class="progress mt-1" data-height="8" style="height: 8px;">
                                <div class="progress-bar l-bg-cyan" role="progressbar" data-width="25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-5 ms-5">
            <div class="card">
                <div class="card-body">
                    <div id="chart-container">
                        <canvas id="chartjs-pie"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Your JavaScript code to create the chart -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    new Chart(document.getElementById("chartjs-pie"), {
      type: "pie",
      data: {
        labels: ["Business Meetups", "IT Conferences", "Social Meetups", "Other"],
        datasets: [{
          data: [260, 125, 54, 146],
          backgroundColor: [
            "#4cc9f0",
            "#f72585",
            "#4361ee",
            "#7209b7"
          ],
          borderColor: "transparent"
        }]
      },
      options: {
        maintainAspectRatio: false,
        cutoutPercentage: 65,
      }
    });
  });
</script>

<style>
  #chart-container {
    width: 100%;
    height: 322px;
  }
</style>

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6">
            <div class="frame">
            <section style="background-color: white; border-radius: 30px;">
  <div class="container pt-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10">
        <div class="card text-body">

          <div class="card-body p-4"  style="background-color: #2ec4b6;">
            <h4 class="mb-0" >Recent comments</h4>
            <p class="fw-light mb-4 pb-2 my-2">Latest Comments section by users</p>

            <div class="d-flex flex-start">
              <div>
                <h6 class="fw-bold mb-1" >{{ comment_first.user.username }}</h6>
                <p class="mb-0">
                    {{ comment_first.comment }}
                </p>
              </div>
            </div>
          </div>

          <hr class="my-0" />

            <hr class="my-0" style="height: 1px;" />
            {% for comment in comments %}
          <div class="card-body p-4 my-2"  style="background-color: #2ec4b6;">
            <div class="d-flex flex-start">
              <div>
                <h6 class="fw-bold mb-1">{{ comment.user.username }}</h6>
                <p class="mb-0">
                  {{ comment.comment }}
                </p>
              </div>
            </div>
          </div>

          <hr class="my-0" />
            {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
            </div>
        </div>
        {% if user.is_authenticated %}
        <div class="col-lg-6">
<div class="comment-prompt">
    <p>Want to say something? Give us a comment.</p>
</div>

<form method="post" class="comment-form mt-5">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Username:</label>
        {{ user.username }}
    </div>
    <div class="form-group">
        <label for="id_comment">Comment:</label>
        {{ form.comment }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

        </div>
        {% else %}
        <div class="col-lg-6">
        <div class="comment-prompt">
            <p>Want to say something? Log in/Register to give us a comment.</p>
        </div>
        </div>
        {% endif %}
    </div>
</div>


{% endblock %}

events/templates/events/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #cbf3f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            max-width: 500px;
            margin-top: 50px;
            background-color: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .container h2 {
            text-align: center;
            margin-bottom: 20px;
            font-weight: 700;
            color: #343a40;
        }
        .form-group label {
            font-weight: 700;
            color: #343a40;
        }
        .btn-primary {
            background-color: #007bff;
            border: none;
            padding: 10px 20px;
            font-weight: 700;
            font-size: 16px;
            width: 100%;
            border-radius: 5px;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
{% endblock %}